apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-todo-app
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-todo-app
  template:
    metadata:
      labels:
        app: spring-todo-app
    spec:
      containers:
        - name: spring-todo-app
          image: janithad/spring-todo-app:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_JPA_SHOW_SQL

            - name: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION

            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/todo_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

            - name: SPRING_MVC_VIEW_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_MVC_VIEW_PREFIX

            - name: SPRING_MVC_VIEW_SUFFIX
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_MVC_VIEW_SUFFIX