apiVersion: v1
kind: Service
metadata:
  name: spring-todo-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: spring-todo-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
